apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hef0u97by-go 
  janus-idp.io/tekton: hef0u97by-go
  backstage.io/kubernetes-id: hef0u97by-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hef0u97by-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  