apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hef0u97by-go
  janus-idp.io/tekton: hef0u97by-go
  backstage.io/kubernetes-id: hef0u97by-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hef0u97by-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
