apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hef0u97by-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hef0u97by-go 
  name: hef0u97by-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hef0u97by-go 
